### ISSUE TITLE
Compression package outdated

### ISSUE THREAD

**Issue by HaoYin116** [zijianchen98/GAIA#3]
I just wanted to mention that the file compression package you provided in your latest post might be outdated. If you could update it, that would be super helpful for everyone following along. Either way, thanks for sharing your knowledge and expertise.

**Comment by zijianchen98** [comment]
Thank you for your interest in our work. I just checked the OneDrive and Baidu Netdisk links, and both can download GAIA.zip normally.

**Comment by HaoYin116** [comment]
But GAIA.zip from OneDrive seems to be corrupted

**Comment by zijianchen98** [comment]
We are considering releasing the dataset on a third party website, please wait a moment

**Comment by zijianchen98** [comment]
We downloaded GAIA.zip (OneDrive) on different devices in different network environments and found that it can be unzipped properly. You may try changing your network environment.
